service: Quiztopia-API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Skola-test
  region: eu-north-1
  iam:
    role: arn:aws:iam::836221056428:role/Lambda-Role

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  addUser:
    handler: functions/signup/index.handler
    events: 
      - httpApi:
          path: '/api/signup'
          method: POST 

  login:
    handler: functions/login/index.handler
    events: 
      - httpApi:
          path: '/api/login'
          method: POST       
  
  getQuizzes:
    handler: functions/getQuizzes/index.handler
    events: 
      - httpApi:
          path: '/api/quiz'
          method: GET 

  getQuiz:
    handler: functions/getQuiz/index.handler
    events: 
      - httpApi:
          path: '/api/quiz/{userId}/{quizId}'
          method: GET 

  addQuiz: 
    handler: functions/addQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz'
          method: POST

  addQuestion: 
    handler: functions/addQuestion/index.handler
    events:
      - httpApi:
          path: '/api/quiz/question'
          method: POST
  
  deleteQuiz: 
    handler: functions/deleteQuiz/index.handler
    events:
      - httpApi:
          path: '/api/quiz/{quizId}'
          method: DELETE

  addPoints: 
    handler: functions/addPoints/index.handler
    events:
      - httpApi:
          path: '/api/leaderbord/{quizId}'
          method: POST

  getTable: 
    handler: functions/getTable/index.handler
    events:
      - httpApi:
          path: '/api/leaderbord/{quizId}'
          method: GET

resources:
  Resources:
    swingDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quiztopia-db
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: userId
            AttributeType: S   
          - AttributeName: name
            AttributeType: S 
        GlobalSecondaryIndexes:
          - IndexName: GSI1-quiz
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: userId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI1-name
            KeySchema:
              - AttributeName: name
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-db
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: userName
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        BillingMode: PAY_PER_REQUEST


